### ISSUE TITLE
Version 1.4.4 for Quilt/Fabric breaks Axes

### ISSUE THREAD

**Issue by sapphiriza** [axperty/cratedelight-fabric#1]
Version 1.4.3 is fine, but 1.4.4 seems to cause axes to completely stop being effective at breaking wooden items. I do have other mods installed (Create, Expanded Delight, Cultural Delight) but I found that when mass-disabling mods to find what caused it, Crate Delight was the root issue. If you need a mod list let me know!

**Comment by axperty** [comment]
Hi sapphiriza,

Please send me the mod names that you're using, it allows me to see the issue as well, I'll try to fix this issue as soon as possible.

Have a good day,
Axperty.

**Comment by axperty** [comment]
The update has been released, now you can play with Crate Delight without any problems when breaking crates, download them here, or just click "Update" on the launcher you play:

[Download on CurseForge](https://www.curseforge.com/minecraft/mc-mods/crate-delight-fabric/files/5230321) | [Download on Modrinth](https://modrinth.com/mod/crate-delight/version/XjYQHLEG)
